language: ruby
cache: bundler
sudo: false

matrix:
  fast_finish: true
  allow_failures:
  include:
    - rvm: jruby-9.0.5.0
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL_TEST=jdbc:postgresql://localhost/nero_test?user=postgres

before_script:
  - psql -c 'create database nero_test;' -U postgres

script: "bin/rspec --tag ~kafka"
