language: ruby
cache: bundler
sudo: false

matrix:
  fast_finish: true
  allow_failures:
  include:
    - rvm: 2.2.1

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database retirement_test;' -U postgres
script: "bin/rspec --tag ~kafka"
