postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=nero"
    - "POSTGRES_PASSWORD=nero"

nero:
  dockerfile: Dockerfile
  build: ./
  env_file:
    - .env
  volumes:
    - ./:/app
  links:
    - postgres
