postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=nero"
    - "POSTGRES_PASSWORD=nero"
  ports:
    - "5432:5432"

zookeeper:
  image: zooniverse/zookeeper
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground -c localhost:2888:3888 -i 1
  ports:
    - "2181:2181"

kafka:
  image: zooniverse/kafka
  links:
    - zookeeper:zk
  hostname: kafka
  command: -i 1 -H kafka -p 9092 -z zk:2181
  ports:
    - "9092:9092"

nero:
  dockerfile: Dockerfile
  build: ./
  environment:
    RAILS_ENV: development
    KAFKA_GROUP: nero-workers
    KAFKA_TOPIC: classifications
  volumes:
    - ./:/app
  links:
    - postgres
    - zookeeper:zk
    - kafka
