postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=nero"
    - "POSTGRES_PASSWORD=nero"
  ports:
    - "5432:5432"

nero:
  dockerfile: Dockerfile
  build: ./
  environment:
    RAILS_ENV: development
  env_file:
    - .env
  volumes:
    - ./:/app
    - ./log/:/var/log/nero
  links:
    - postgres
