postgres:
  image: zooniverse/postgresql
  environment:
    - "PG_USER=retirement_swap"
    - "DB=retirement_swap_development"
    - "PASS=retirement_swap"
  ports:
    - "5432:5432"

zookeeper:
  image: zooniverse/zookeeper
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground -c localhost:2888:3888 -i 1
  ports:
    - "2181:2181"

kafka:
  image: zooniverse/kafka
  links:
    - zookeeper:zk
  hostname: kafka
  command: -i 1 -H kafka -p 9092 -z zk:2181
  ports:
    - "9092:9092"

retirementswap:
  dockerfile: Dockerfile
  build: ./
  environment:
    KAFKA_GROUP: retirement-swap-workers
    KAFKA_TOPIC: classifications
  command: ruby -I /app/lib /app/bin/start
  volumes:
    - ./:/app
  links:
    - postgres
    - zookeeper:zk
    - kafka
