development:
  adapter: postgres
  host: localhost
  database: nero_development
  user: marten
  password:

test:
  adapter: postgres
  host: localhost
  database: nero_test
  user: marten
  password:

staging:
  adapter: postgres
  host: localhost
  database: nero_staging
  user: marten
  password:

production:
  adapter: postgres
  host: localhost
  database: nero_production
  user: marten
  password:
