development:
  adapter: jdbc
  uri: jdbc:postgresql://postgres/nero_development?user=nero&password=nero

test:
  adapter: jdbc
  uri: jdbc:postgresql://postgres/nero_test?user=nero&password=nero

staging:
  adapter: jdbc
  uri: jdbc:postgresql://postgres/nero_staging?user=nero&password=nero

production:
  adapter: jdbc
  uri: jdbc:postgresql://postgres/nero_production?user=nero&password=nero
