development:
  adapter: postgres
  host: postgres
  database: nero_development
  user: nero
  password: nero

test:
  adapter: postgres
  host: postgres
  database: nero_test
  user: nero
  password: nero

staging:
  adapter: postgres
  host: postgres
  database: nero_staging
  user: nero
  password: nero

production:
  adapter: postgres
  host: postgres
  database: nero_production
  user: nero
  password: nero
