development:
  adapter: postgres
  host: postgres
  database: retirement_swap_development
  user: retirement_swap
  password: retirement_swap

test:
  adapter: postgres
  host: postgres
  database: retirement_swap_test
  user: retirement_swap
  password: retirement_swap

staging:
  adapter: postgres
  host: postgres
  database: retirement_swap_staging
  user: retirement_swap
  password: retirement_swap

production:
  adapter: postgres
  host: postgres
  database: retirement_swap_production
  user: retirement_swap
  password: retirement_swap
