development:
  consumer_group: nero-development
  topic: classifications
  zookeepers:
    - zk:2181
  brokers:
    - kafka:9092

test:
  consumer_group: nero-test
  topic: classifications
  zookeepers:
    - zk:2181
  brokers:
    - localhost:9092
