development:
  consumer_group: retirement-swap-development
  topic: classifications
  zookeepers:
    - zk:2181
  brokers:
    - kafka:9092

test:
  consumer_group: retirement-swap-test
  topic: classifications
  zookeepers:
    - zk:2181
  brokers:
    - localhost:9092
