---
development:
  5101a1341a320ea77f000001:
    algorithm: swap
  1021:
    algorithm: snapshot_wisconsin
  1224:
    algorithm: pulsar_hunters
    gold_standard_limit: 150
    normal_limit: 50

test:
  5101a1341a320ea77f000001:
    algorithm: swap

staging:
  2661:
    algorithm: transcribe_hack

production:
  1217:
    algorithm: snapshot_wisconsin
  1224:
    algorithm: pulsar_hunters
    gold_standard_limit: 50
    normal_limit: 50
  1432:
    algorithm: survey
    task_key: T1
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 3
    blank_consensus_limit: 5
  1643:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  1717:
    algorithm: snapshot_wisconsin
  1810:
    algorithm: equador
  2245:
    algorithm: blank
    task_key: T1
    blank_consensus_limit: 5
  2334:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 3
    blank_consensus_limit: 5
  2647:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  2672:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  2731:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  2855:
    algorithm: survey
    task_key: T1
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 3
    blank_consensus_limit: 5
  2863:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  3054:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 3
    blank_consensus_limit: 5
  3206:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  3207:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  3208:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  3209:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
  3210:
    algorithm: survey
    task_key: T0
    consensus_limit: 7
    human_limit: 1
    vehicle_limit: 1
    flagged_limit: 1
    blank_limit: 1
    blank_consensus_limit: 5
