---
development:
  5101a1341a320ea77f000001:
    algorithm: swap
  1021:
    algorithm: snapshot_wisconsin
  1224:
    algorithm: pulsar_hunters
    gold_standard_limit: 150
    normal_limit: 50
test:
  5101a1341a320ea77f000001:
    algorithm: swap
staging: {}
production:
  1717:
    algorithm: snapshot_wisconsin
  1217:
    algorithm: snapshot_wisconsin
  1224:
    algorithm: pulsar_hunters
    gold_standard_limit: 50
    normal_limit: 50
  1810:
    algorithm: equador
